# Generated by Django 2.2.1 on 2019-05-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0003_auto_20190526_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='published_by',
            field=models.CharField(default='Everton News', max_length=20),
        ),
    ]
