# Generated by Django 2.2.1 on 2019-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0004_newspost_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='thumbnail_url',
            field=models.CharField(default='img/defaults/default_thumbnail.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
