# Generated by Django 2.2.1 on 2019-06-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0009_auto_20190602_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_on'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='playertransfers',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Player Transfers'},
        ),
        migrations.RemoveField(
            model_name='playertransfers',
            name='type',
        ),
    ]
