# Generated by Django 2.2.1 on 2019-06-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0010_auto_20190613_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransfers',
            name='type',
            field=models.CharField(choices=[('1', 'Transfer In'), ('2', 'Transfer Out'), ('3', 'Loan In'), ('4', 'Loan Out'), ('5', 'In F/A'), ('6', 'Released')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
