# Generated by Django 2.2.1 on 2019-06-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0011_playertransfers_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertransfers',
            name='type',
        ),
    ]
