# Generated by Django 2.2.1 on 2019-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0012_remove_playertransfers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransfers',
            name='type',
            field=models.CharField(choices=[('1', 'Transfer In'), ('2', 'Transfer Out'), ('3', 'Loan In'), ('4', 'Loan Out'), ('5', 'In F/A'), ('6', 'Released')], default='Transfer In', max_length=250),
        ),
    ]
