# Generated by Django 2.2.1 on 2019-06-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0013_playertransfers_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertransfers',
            options={'ordering': ['date'], 'verbose_name_plural': 'Player Transfers'},
        ),
    ]
