# Generated by Django 2.2.1 on 2019-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0014_auto_20190615_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(default='img/article_images/default.jpg', upload_to='img/article_images'),
        ),
    ]
