# Generated by Django 2.2.1 on 2019-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0015_newspost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='everton.Tag'),
        ),
    ]
