# Generated by Django 2.2.1 on 2019-07-05 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0016_auto_20190627_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('homebadge', models.CharField(default='img/team-badges/default.jpg', max_length=50)),
                ('awaybadge', models.CharField(default='img/team-badges/default.jpg', max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('1', 'League'), ('2', 'Friendly'), ('3', 'Cup')], default='Transfer In', max_length=250)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
