# Generated by Django 2.2.1 on 2019-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everton', '0017_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='title',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_abrv',
            field=models.CharField(default='LFC', max_length=80),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_name',
            field=models.CharField(default='Liverpool', max_length=80),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_abrv',
            field=models.CharField(default='EFC', max_length=80),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_name',
            field=models.CharField(default='Everton', max_length=80),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awaybadge',
            field=models.CharField(default='img/team-badges/default.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='homebadge',
            field=models.CharField(default='img/team-badges/default.png', max_length=50),
        ),
    ]
